--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/alexbgameson/3.0.0Alpha9-PocketMine-Plugins
branches:
- master
projects:
  2vs2:
    path: 2vs2/
  BoostPad:
    path: BoostPad/
  CrateKeys:
    path: CrateKeys/
  CustomHelp:
    path: CustomHelp/
  JoinSystem:
    path: JoinSystem/
  KillCash:
    path: KillCash/
  KitUI:
    path: KitUI/
  KnockbackFFA:
    path: KnockbackFFA/
  MineReset:
    path: MineReset/
  Multi-Inv:
    path: Multi-Inv/
  MultiWorld:
    path: MultiWorld/
  PVPlevelRPG:
    path: PVPlevelRPG/
  PeacefulSpawn:
    path: PeacefulSpawn/
  PerWorldChat:
    path: PerWorldChat/
  PlayerVaults:
    path: PlayerVaults/
  RankUp:
    path: RankUp/
  SkyBlock:
    path: SkyBlock/
  SoupFFA:
    path: SoupFFA/
  StatsPE-master:
    path: StatsPE-master/
  SuperVanish:
    path: SuperVanish/
  TapToDo:
    path: TapToDo/
  TeaSpoon:
    path: TeaSpoon/
  TimeCommander:
    path: TimeCommander/
...
