name: PerWorldChat
main: PerWorldChat\Main
version: "0.2.1"
api:
 - 3.0.0
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
 - 3.0.0-ALPHA12
authors:
 - EvolSoft
 - jasonwynn10
description: "Per-World Chat"
