name: PVPlevelRPG
main: LevelMain\Main
description: Plugin for server that want an Level systeme
version: 8.5
api: [2.0.0,1.0.0,3.0.0-ALPHA1,3.0.0-ALPHA2,3.0.0-ALPHA3,3.0.0-ALPHA10,3.0.0-ALPHA11,3.0.0]
