# Configuration file for JoinSystem
# JoinSystem by @McpeBooster

#If you need help, look at the ReadMe.md
#After every change here, restart the Server!


#Fill here the Lobby world in:
Lobby: debug123

#The JoinMessage:
JoinMsg: ยง2+ ยง6{player}

#The QuitMessage
QuitMsg: ยงc+ ยง6{player}