name: TimeCommander
main: LDX\TimeCommander\Main
author: "LDX"
version: 2.2
api:
 - 3.0.0
 - 3.0.0-ALPHA9
 - 3.0.0-ALPHA10
 - 3.0.0-ALPHA11
 - 3.0.0-ALPHA12
load: POSTWORLD
website: "https://github.com/LDX-MCPE/TimeCommander"
